spring:
  application:
    name: config
    
# 服务名称 和 数据库
spring:
  application:
    name: oeder
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://211.159.173.163:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: niaoren123456
  # 使用jpa插件
  jpa:
    show-sql: true

server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/