#服务端口号
server:
  port: 8882

# 服务名称 和 数据库
spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://211.159.173.163:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: niaoren123456
  # 使用jpa插件
  jpa:
    show-sql: false
  rabbitmq:
   host: localhost
   port: 5672
   username: guest
   password: guest
